### ISSUE TITLE
Display hash value in standard PHC String Format

### ISSUE THREAD

**Issue by sanmai-NL** [bryant/argon2rs#30]
Add a type for hash values, impl `Display` for that type. The `display` method should print. See: https://github.com/P-H-C/phc-string-format/blob/master/phc-sf-spec.md

**Comment by bryant** [comment]
Just from a cursory glance through that link, it looks a lot like what `argon2rs::verifier` emits. Have you seen that module?

**Comment by bryant** [comment]
Yeah, this is exactly what verifier does. Closing this unless I've missed something critical, in which case please let me know.
