### ISSUE TITLE
Update to `ARGON_VERSION_13` (version 19).

### ISSUE THREAD

**Issue by bryant** [bryant/argon2rs#4]

**Comment by bryant** [comment]
- Blocks the crates.io release.
- Decide whether to keep the older implementation (this could complicate the design as a version enum would need to be passed along to API calls).

**Comment by chpio** [comment]
the current version (0x10?) and this version are incompatible, i guess?! What do you think could be done to make them compatible/update from the older one to the newer? Im using the `Verifier` to verify user passwords, so i would update the hash (the result of `Verifier::to_u8`) on logins. But how can i install two versions of this crate, so i can check the old version but also generate hashes with the newer version?

**Comment by chpio** [comment]
Using this suggestion: https://users.rust-lang.org/t/installing-the-same-crate-multiple-times-with-different-versions/7026/4 there would be no need for "keeping the older implementation". There would be a proxy crate with would reexport Argon2 as *argon2v0x13* and *argon2v0x19* (or something else :))

**Comment by markuskobler** [comment]
Whats the plan with supporting Version `0x13` it looks like it was merged and then removed from the repo?
